db:
  production:
    adapter:    mysql2
    host:       <%= ENV["MYSQL_HOST"] %>
    username:   <%= ENV["MYSQL_USER"] %>
    password:   <%= ENV["MYSQL_PASSWORD"] %>
    database:   <%= ENV["MYSQL_DATABASE"] %>
    encoding:   utf8mb4
    charset:    utf8mb4
    collation:  utf8mb4_general_ci
  development:
    adapter:    mysql2
    host:       <%= ENV["MYSQL_HOST"] %>
    username:   <%= ENV["MYSQL_USER"] %>
    password:   <%= ENV["MYSQL_PASSWORD"] %>
    database:   <%= ENV["MYSQL_DATABASE"] %>
    encoding:   utf8mb4
    charset:    utf8mb4
    collation:  utf8mb4_general_ci
